name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    uses: xonsh/actions/.github/workflows/test-poetry-xontrib.yml@main
    with:
      xontrib_name: jedi
